import './env-init.ts';
import fs from 'fs';
import path from 'path';
import { SitemapStream, streamToPromise } from 'sitemap';
// Avoid importing TypeScript source (Node ESM resolver won't load .ts by default).
// Instead, leverage the precompiled search data produced earlier in the build.
interface PostMeta {
  slug: string;
  title: string;
  date: string; // ISO
  timezone: string;
  excerpt?: string;
  tags?: string[];
  author: string;
  thumbnail?: string;
  width?: string;
}

function getAuthorSlug(author: string): string {
  return author.toLowerCase().replace(/\s+/g, '-');
}

function tagToSlug(tag: string): string {
  return tag.toLowerCase().replace(/ /g, '-');
}

const baseUrl = process.env.BASE_URL || 'https://dhugs.com';

async function generateSitemap() {
  // Load precompiled search metadata (generated by precompile-posts script)
  const searchDataPath = path.join(process.cwd(), 'data', 'search-data.json');
  let posts: PostMeta[] = [];
  try {
    const raw = fs.readFileSync(searchDataPath, 'utf8');
    const parsed = JSON.parse(raw);
    posts = Array.isArray(parsed.posts) ? parsed.posts : [];
  } catch (e) {
    console.warn('Could not load search-data.json; sitemap will include only static pages.', e);
  }
  const sitemap = new SitemapStream({ hostname: baseUrl });

  // Add static pages with balanced priorities
  sitemap.write({ url: '/', changefreq: 'daily', priority: 1.0 });
  sitemap.write({ url: '/about', changefreq: 'monthly', priority: 0.9 });
  sitemap.write({ url: '/portfolio', changefreq: 'monthly', priority: 0.9 });
  sitemap.write({ url: '/privacy-policy', changefreq: 'monthly', priority: 0.5 });

  // New: Additional static pages balanced for SEO
  sitemap.write({ url: '/archive', changefreq: 'weekly', priority: 0.7 });
  sitemap.write({ url: '/author', changefreq: 'weekly', priority: 0.6 });
  sitemap.write({ url: '/category', changefreq: 'weekly', priority: 0.6 });
  sitemap.write({ url: '/recent', changefreq: 'weekly', priority: 0.7 });

  // Add dynamic posts with balanced priority
  const yearArchives = new Set();
  const monthArchives = new Set();
  
  posts.forEach(post => {
    const postDate = new Date(post.date);
    const year = postDate.getFullYear();
    const month = postDate.toLocaleString('en-US', {
      timeZone: 'America/New_York',
      month: '2-digit'
    });
    
    // Add full post URL with trailing slash
    sitemap.write({ 
      url: `/${year}/${month}/${post.slug}/`, 
      changefreq: 'weekly', 
      priority: 0.8 
    });

    // Only add year/month archive pages if we have content
    yearArchives.add(year);
    monthArchives.add(`${year}/${month}`);
  });

  // Add year archive pages
  yearArchives.forEach(year => {
    sitemap.write({ 
      url: `/${year}/`,
      changefreq: 'monthly',
      priority: 0.6 
    });
  });

  // Add month archive pages 
  monthArchives.forEach(monthPath => {
    sitemap.write({ 
      url: `/${monthPath}/`,
      changefreq: 'monthly', 
      priority: 0.6 
    });
  });

  // Dynamic author and category (tag) pages with balanced priority
  const authors = new Set<string>();
  const categories = new Set<string>();
  posts.forEach(post => {
    if (post.author) authors.add(getAuthorSlug(post.author));
    if (post.tags && Array.isArray(post.tags)) {
      post.tags.forEach(tag => categories.add(tagToSlug(tag)));
    }
  });
  authors.forEach(author => {
    sitemap.write({ url: `/author/${encodeURIComponent(author)}/`, changefreq: 'weekly', priority: 0.7 });
  });
  categories.forEach(category => {
    sitemap.write({ url: `/category/${encodeURIComponent(category)}/`, changefreq: 'weekly', priority: 0.7 });
  });

  sitemap.end();

  const sitemapPath = path.join(process.cwd(), 'public', 'sitemap.xml');
  const sitemapData = await streamToPromise(sitemap).then(sm => sm.toString());
  fs.writeFileSync(sitemapPath, sitemapData);
  console.log(`Sitemap written to ${sitemapPath}`);

  // New: generate robots.txt using BASE_URL from .env.local
  const robotsTxtContent = `User-agent: *
Disallow:

Sitemap: ${baseUrl}/sitemap.xml`;
  const robotsTxtPath = path.join(process.cwd(), 'public', 'robots.txt');
  fs.writeFileSync(robotsTxtPath, robotsTxtContent);
  console.log(`robots.txt written to ${robotsTxtPath}`);
}

generateSitemap().catch(error => {
  console.error('Error generating sitemap:', error);
  process.exit(1);
});
